# AUTOGRAD: AUTOMATIC DIFFERENTIATION

In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


`.requires_grad_( ... )` changes an existing Tensor's `requires_grad` flag in-place. The input flag defaults to `False` if not given.

In [6]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


as `out` contains a single scalar, `out.backward()` is equivalent to `out.backward(torch.tensor(1.))`.

In [7]:
out.backward()

You should have got a matrix of 4.5. Let’s call the out Tensor “o”. We have that o=1/4∑izi, zi=3(xi+2)^2 and zi∣∣xi=1=27. Therefore, ∂o/∂xi=3/2(xi+2), hence ∂o/∂xi∣∣xi=1= 9/2=4.5.

In [8]:
print(x)
print(x.grad_fn)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


Example of vector-Jacobian product:

In [9]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([1012.7282,   -9.1643, -305.3846], grad_fn=<MulBackward0>)


Now in this case `y` is no longer a scalar. `torch.autograd` could not compute the full Jacobian directly, but if we just want the vector-Jacobian product, simply pass the vector to `backward` as argument:

In [10]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


Document about `autograd.Function` is at https://pytorch.org/docs/stable/autograd.html#function