# Tensors

Tensors are similar to Numpy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[4.7414e+16, 3.1434e-12, 8.0775e+17],
        [1.4583e-19, 4.1486e-08, 1.3556e-19],
        [1.8567e-01, 1.2043e-32, 1.3563e-19],
        [1.8888e+31, 4.7414e+16, 4.0047e-11],
        [6.4097e-10, 5.8253e-10, 6.4097e-10]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.6808, 0.5723, 0.5622],
        [0.5743, 0.2358, 0.7511],
        [0.4627, 0.1708, 0.4256],
        [0.0585, 0.8490, 0.6880],
        [0.1732, 0.9819, 0.6814]])


In [4]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct cell directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Create a tensor based on existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5937,  0.4285,  0.7954],
        [-0.9690, -0.1389, -0.1291],
        [ 0.9000,  0.4680,  0.1969],
        [ 1.1554,  1.2458,  1.2621],
        [-0.7555,  1.3759, -0.3930]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5,3)
print(y)
print(x + y)


tensor([[0.3707, 0.3115, 0.8513],
        [0.0872, 0.1580, 0.5544],
        [0.3474, 0.5298, 0.1168],
        [0.0637, 0.6422, 0.0818],
        [0.4011, 0.7206, 0.8420]])
tensor([[ 0.9644,  0.7399,  1.6467],
        [-0.8818,  0.0191,  0.4253],
        [ 1.2475,  0.9978,  0.3137],
        [ 1.2191,  1.8880,  1.3439],
        [-0.3544,  2.0966,  0.4490]])


In [9]:
result = torch.zeros(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.9644,  0.7399,  1.6467],
        [-0.8818,  0.0191,  0.4253],
        [ 1.2475,  0.9978,  0.3137],
        [ 1.2191,  1.8880,  1.3439],
        [-0.3544,  2.0966,  0.4490]])


Addition: in-place

In [10]:
y.add_(x)
print(y)

tensor([[ 0.9644,  0.7399,  1.6467],
        [-0.8818,  0.0191,  0.4253],
        [ 1.2475,  0.9978,  0.3137],
        [ 1.2191,  1.8880,  1.3439],
        [-0.3544,  2.0966,  0.4490]])


### CUDA Tensors

In [11]:
print(torch.cuda.is_available())
print(torch.backends.cudnn.enabled)
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

True
True
tensor([[1.5937, 1.4285, 1.7954],
        [0.0310, 0.8611, 0.8709],
        [1.9000, 1.4680, 1.1969],
        [2.1554, 2.2458, 2.2621],
        [0.2445, 2.3759, 0.6070]], device='cuda:0')
tensor([[1.5937, 1.4285, 1.7954],
        [0.0310, 0.8611, 0.8709],
        [1.9000, 1.4680, 1.1969],
        [2.1554, 2.2458, 2.2621],
        [0.2445, 2.3759, 0.6070]], dtype=torch.float64)
